ranky:
    build: .
    dockerfile: Dockerfile-dev
    volumes:
        - app:/src/app
    links:
        - db
    ports:
        - "3000:3000"
    environment:
        NODE_ENV: development
db:
    image: postgres:9.4
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: ranky
        POSTGRES_PASSWORD: 12345q
