FROM node:0.10

RUN apt-get update -qq && apt-get install -y build-essential
RUN apt-get install -y ruby

RUN mkdir /src

RUN npm install gulp -g

WORKDIR /src
ADD app /src/
RUN npm install

EXPOSE 3000
EXPOSE 35729

#CMD tail -f package.json
CMD node app.js
