ranky:
    build: .
    volumes:
        - .:/src
    links:
        - mongo
    ports:
        - "3000:3000"
    environment:
        NODE_ENV: development
mongo:
    image: mongo
    ports:
        - "27017:27017"
