ranky:
    build: .
    volumes:
        - app:/src/app
    links:
        - mongo
    ports:
        - "3000:3000"
    environment:
        NODE_ENV: development
mongo:
    image: mongo
    volumes:
        - mongodb:/var/lib/mongodb
    ports:
        - "27017:27017"
    command: mongod --smallfiles --quiet --logpath=/dev/null
