#!/bin/zsh                                                                                                   

SESSIONNAME="ranky"
SN=$SESSIONNAME
alias tmux="TERM=screen-256color-bce tmux"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ] 
  then
    tmux new-session -s $SN -n editor -d
    tmux send-keys -t $SN "vim" C-m 
    tmux split-window -v -t $SN
    tmux resize-pane -t 2 -y 3
    tmux send-key -t $SN:1.2 'npm run autotest' C-m
    tmux new-window -n console -t $SN
    tmux send-key -t $SN:2.1 'git status' C-m
    tmux split-window -h -t $SN
    tmux send-key -t $SN:2.2 'nodemon --debug app.js' C-m
    tmux split-window -v -t $SN
    tmux select-pane -U
    tmux select-window -t $SN:1
    tmux select-pane -U
fi

tmux attach -t $SESSIONNAME -d
